services:
  grafana:
    image: grafana/grafana:11.0.0
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      GF_SMTP_ENABLED: ${GF_SMTP_ENABLED:-true}
      GF_SMTP_HOST: ${GF_SMTP_HOST:-smtp.gmail.com:587}
      GF_SMTP_USER: ${GF_SMTP_USER:-insert email}
      GF_SMTP_FROM_ADDRESS: ${GF_SMTP_FROM_ADDRESS:-insert email}
      GF_SMTP_FROM_NAME: ${GF_SMTP_FROM_NAME:-Grafana}
      GF_SMTP_PASSWORD: ${GF_SMTP_PASSWORD:-insert gmail app password}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning:ro

  loki:
    image: grafana/loki:3.0.0
    restart: unless-stopped
    command: -config.file=/etc/loki/config.yaml
    expose:
      - "3100"
    volumes:
      - ./config/loki/config.yaml:/etc/loki/config.yaml:ro
      - loki-data:/loki

  tempo:
    image: grafana/tempo:2.10.0
    restart: unless-stopped
    command:
      - -config.file=/etc/tempo/config.yaml
    expose:
      - "3200"
      - "4318"
    volumes:
      - ./config/tempo/config.yaml:/etc/tempo/config.yaml:ro
      - tempo-data:/var/tempo

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/config.yaml
      - --storage.tsdb.path=/prometheus
    expose:
      - "9090"
    volumes:
      - ./config/prometheus/config.yaml:/etc/prometheus/config.yaml:ro
      - prometheus-data:/prometheus

  alloy:
    image: grafana/alloy:latest
    restart: unless-stopped
    command: run /etc/alloy/config.alloy
    expose:
      - "12345"
    volumes:
      - ./config/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log:/var/log:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/log/journal:/var/log/journal:ro
      - /run/log/journal:/run/log/journal:ro

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    restart: unless-stopped
    expose:
      - "8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      
networks:
  default:
    name: system-proxy
    # mark this as external outside of system/compose.yaml so that the network isn't duplicated...
    external: true

volumes:
  grafana-data:
  loki-data:
  tempo-data:
  prometheus-data: