# The services defined here internally use service names to communicate with each other: ie. grafana:3000
# Docker resolves service names to IPs only when they are in the same *user defined* bridge network.
# So, make sure they are all in the system-proxy network or some other *user defined* network.
services:
  grafana:
    image: grafana/grafana:11.0.0
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      GF_SMTP_ENABLED: ${GF_SMTP_ENABLED:-true}
      GF_SMTP_HOST: ${GF_SMTP_HOST:-smtp.gmail.com:587}
      GF_SMTP_USER: ${GF_SMTP_USER:-insert email}
      GF_SMTP_FROM_ADDRESS: ${GF_SMTP_FROM_ADDRESS:-insert email}
      GF_SMTP_FROM_NAME: ${GF_SMTP_FROM_NAME:-Grafana}
      GF_SMTP_PASSWORD: ${GF_SMTP_PASSWORD:-insert gmail app password}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning:ro

  loki:
    image: grafana/loki:3.0.0
    restart: unless-stopped
    command: -config.file=/etc/loki/config.yaml
    expose:
      - "3100"
    volumes:
      - ./config/loki/config.yaml:/etc/loki/config.yaml:ro
      - loki-data:/loki

  tempo:
    image: grafana/tempo:2.10.0
    restart: unless-stopped
    command:
      - -config.file=/etc/tempo/config.yaml
    expose:
      - "3200"
      - "4318"
    volumes:
      - ./config/tempo/config.yaml:/etc/tempo/config.yaml:ro
      - tempo-data:/var/tempo

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/config.yaml
      - --storage.tsdb.path=/prometheus
    expose:
      - "9090"
    volumes:
      - ./config/prometheus/config.yaml:/etc/prometheus/config.yaml:ro
      - prometheus-data:/prometheus

  alloy:
    image: grafana/alloy:latest
    restart: unless-stopped
    command: run /etc/alloy/config.alloy
    expose:
      - "12345"
    volumes:
      - ./config/alloy/config.alloy:/etc/alloy/config.alloy:ro      # Alloy config file
      - /var/run/docker.sock:/var/run/docker.sock:ro                # Docker sock connection
      - /etc/machine-id:/etc/machine-id:ro                          # host machine id
      - /var/log:/var/log:ro                                        # host log folder              
      - /var/log/journal:/var/log/journal:ro                        # host persisntent journal log file (this is actually redundant since we mounted the whole folder)
      - /run/log/journal:/run/log/journal:ro                        # host in-memory journal log file
      # note: we use system_logs_npm instead of logs_npm since compose stack name is prepended to volume names...
      - system_logs_npm:/logs/npm:ro                                # custom log file: ie. npm log files (npm container also mounts logs_npm, where it stores logs).

  # Container Advisor. For container metrics.
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    restart: unless-stopped
    expose:
      - "8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro

  # node is a "server node," not to be confused with NodeJS :)
  # it reads host resource metrics like CPU, RAM usage and exposes them to Prometheus in a format that it understands.
  node-exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    expose:
      - "9100"
    command:
      - --path.rootfs=/host
    volumes:
      - /:/host:ro,rslave

networks:
  default:
    name: system-proxy
    # mark this as external outside of system/compose.yaml so that the network isn't duplicated...
    external: true

volumes:
  system_logs_npm:
    # set true outside of the "system" stack to prevent duplication
    external: true
  grafana-data:
  loki-data:
  tempo-data:
  prometheus-data: