global:
  scrape_interval: 15s

# Notes:

# Prometheus adds the following labels to metrics data by default:
#   - job: {job_name}
#   - instance: {target}
# so a metric entry may look like { job: "grafana", instance: "grafana:3000" }

# Metrics_path is /metrics by default but can be overriden like:
#   - job_name: grafana
#     metrics_path: /custom-

# Two different scrape jobs may collect a metric by the same name.
# You can differentiate them by the job label or other labels if needed.

scrape_configs:
  # You can observe the observability stack metrics itself! But I disabled it by default.
  # - job_name: grafana
  #   static_configs:
  #     - targets: ["grafana:3000"]

  # - job_name: alloy
  #   static_configs:
  #     - targets: ["alloy:12345"]

  # - job_name: prometheus
  #   static_configs:
  #     - targets: ["prometheus:9090"]

  # - job_name: loki
  #   static_configs:
  #     - targets: ["loki:3100"]

  # - job_name: tempo
  #   static_configs:
  #     - targets: ["tempo:3200"]

  # Container Advisor. For container metrics.
  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]

  # node is a "server node," not to be confused with NodeJS :)
  # it reads resource metrics from host and exposes them to Prometheus in a format that it understands.
  - job_name: node
    static_configs:
      - targets: ["node-exporter:9100"]